### PR TITLE
[Facets] update visual representation of facets operators

### PR DESCRIPTION
**Pull request by patrickracicot**
### PR Summary: 

Added visual changes to filters that have the AND operator.  The goal of this change is to add a subtitle to filters that have the `AND` operator associated to them as well as keeping the selected values for these filters grouped.

### Why are these changes introduced?

Following the introduction of the AND operator to certain filter types it was deemed to subtle to only use the dynamic counts to inform buyers when a filter is using the new logical operator.  After various tries and prototypes, the final decision was to add a subtitle as well as group the selected filter values.

### Testing steps/scenarios

- [ ] Install the [1P app Search & Discovery ](https://apps.shopify.com/search-and-discovery?search_id=f8922d74-7041-40da-92db-41957c14d188&surface_detail=search+%26+discovery&surface_inter_position=1&surface_intra_position=4&surface_type=search)
- [ ] Create a new filter using the `tags` filter type
- [ ] Change the logical operator to `AND`
- [ ] On the online store, apply the tags filter
- [ ] Ensure that the selected filter values are grouped and kept at the start of the list

### Demo links

- [Store](https://collect-payment-a11y.myshopify.com/)
- [Editor](https://admin.shopify.com/store/collect-payment-a11y/themes/157789454358/editor)

### Checklist
- [x] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [x] Requested review from UX (Only for changes that are affecting the experience or perceivable visual details)
- [-] Created a ticket for the [help.shopify.com](https://help.shopify.com) documentation team about updates to theme settings. (Internal-only task)
- [x] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [x] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [x] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [x] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [x] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

### CODE REVIEW

**Comment by dan-menard** [comment]
One thing I noticed while 🎩, this spinner in the top-right corner never stops spinning:

image

Seems to work well otherwise tho, so if that's a known issue we're good 👍

**Review by dan-menard — APPROVED** [review]

**Comment by jas7457** [comment]
Just noticed this, seems likely it happened when you changed from div to span. There's a css rule that puts a text-decoration: underline of any span in that summary.

I think the proper fix is to not target any span, but a specific class, for this css.

image

**Comment by patrickracicot** [comment]
> Just noticed this, seems likely it happened when you changed from div to span. There's a css rule that puts a text-decoration: underline of any span in that summary.
> 
> I think the proper fix is to not target any span, but a specific class, for this css.
> 

Fixed it by adding a css class to the label span and making the CSS selector use that class instead of element selectors.  This should also prevent similar issues in the future.

**Review by jas7457 — APPROVED** [review]
LGTM!

**Pull request merged**
