### PR TITLE
Quick add bulk bug fixes

### PR DESCRIPTION
**Pull request by sofiamatulis**
### PR Summary: 

After: https://screenshot.click/26-07-ko0lt-yvku0.mp4
Before: https://screenshot.click/26-05-v638m-cp0yd.mp4 and https://screenshot.click/26-06-aamzi-sfk83.mp4

1 - Allow for the buyer to add more items to cart from other variants when +/- is updating the cart (dont block the cursor)- which is the same experience for keyboard navigation

Original bug: When an item is being added to the cart via +/-, I can't click on any other plus/minuses. [See Video](https://screenshot.click/26-05-v638m-cp0yd.mp4)

2 - Ensure the input focus goes back in when the keyboard navigation goes to the previous element that is being updated

Reproduction steps: The input loses focus when
i) Focus on an input  
ii) Type value  
iii) Press enter (Focus shifts to next input)  
iv) Press shift enter while cart request is still spinning  
v) Input loses focus when cart request comes back
[See video](https://screenshot.click/26-06-aamzi-sfk83.mp4)

### Demo links

Test QOL and Quick Add Bulk (same component)
- [Editor](https://admin.shopify.com/store/os2-demo/themes/163059826710/editor)

### Checklist
- [ ] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [ ] Requested review from UX (Only for changes that are affecting the experience or perceivable visual details)
- [ ] Created a ticket for the [help.shopify.com](https://help.shopify.com) documentation team about updates to theme settings. (Internal-only task)
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

### CODE REVIEW

**Comment by scottgmeadows** [comment]
Seeing some blocking issues on both fixes.

**#1** - If I click rapidly through multiple inputs, the quantity changes but we don't actually update the cart - eg. no trash icon. [See video](https://screenshot.click/27-43-ap6tj-58csd.mp4)

**#2** - If I enter a quantity, hit enter then, shift enter, the input focus jumps back to the next row when the next row's item is added to the cart. [See video](https://screenshot.click/27-44-zjd7y-ybk2b.mp4)

**Comment by sofiamatulis** [comment]
> Currently if I change a value and focus the next row, my focus goes back to the re-rendered row which is not the desired UX. The current focus experience is less broken that what we had but imo still not what we want.

What do you mean by this exactly?

So this approach wouldnt work because: https://screenshot.click/27-07-kelhx-2639y.mp4

**Comment by tyleralsbury** [comment]
> Seeing a weird bug where some quantity inputs stop working correctly after using remove all.
> 
> [See video](https://screenshot.click/28-44-4fcin-tvlht.mp4)

Probably just needs to re-attach all events - I assume you're reloading all the rows at that point.

**Comment by scottgmeadows** [comment]
> > Seeing a weird bug where some quantity inputs stop working correctly after using remove all.
> > [See video](https://screenshot.click/28-44-4fcin-tvlht.mp4)
> 
> @scottgmeadows Yes, this is fixed already. Can you re-try? https://screenshot.click/28-11-hxh8g-b6x6r.mp4

Seems fixed now :)

**Pull request merged**
