### PR TITLE
Add info for the custom liquid section

### LINKED ISSUE #299: Add Help text to Custom Liquid Section + Block
Relates to: https://github.com/Shopify/dawn/issues/42

**Describe the enhancement you'd like**

We have an opportunity to better inform merchants on the usecases in which they add an custom liquid section:
- Add your own Liquid
- Add an app's liquid snippet

@gretchen-willenberg Could you help come up with copy for this? 

image

### PR DESCRIPTION
**Pull request by ludoboludo**
**Why are these changes introduced?**

Fixes #299 

**What approach did you take?**

Add info text as suggested in the issue. 

**Other considerations**

There is already a link to some liquid help doc based on the type of the setting. If we want to change that, I'm going to have to reach out to another team I believe. 

**Demo links**

- [Store](url)
- [Editor](url)

**Checklist**
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

### CODE REVIEW

**Review by gretchen-willenberg — APPROVED** [review]
No changes. Some day, in a much later cycle, we may update that Editor link ("Learn about Liquid")? That pattern now seems old and now sticks out from most other blocks/sections.

**Comment by ludoboludo** [comment]
@gretchen-willenberg how do you feel about updating the copy to follow Paul's suggestion in the issue. So it would become: 
`Add Liquid code or snippets from apps and other sources to create advanced customizations.`

I think he makes some great points in [his comment here](https://github.com/Shopify/dawn/issues/299#issuecomment-892232117).

**Comment by gretchen-willenberg** [comment]
Thanks, definitely. I reviewed the feedback, shared it with the docs team to double-check the merchant-facing docs that will be released when Dawn is include relevant information, and reconsidered draft placeholder copy that needs further team input (what is an appropriate example vs something that a merchant should be encouraged to use a metafield for, etc). 

As long as you're comfortable with opening the door to `snippets from...other sources` as this was not included in the primary use cases ([issue 299](https://github.com/Shopify/dawn/issues/299#issuecomment-892232117)):

Block name: `Custom Liquid`
Setting Label: `Custom Liquid`
Setting link from Editor: `[Learn more about Liquid](url)`
[input]
Support text: `Add Liquid code or snippets from apps and other sources to create advanced customizations.`

The block name, setting label, and setting link provide solid context on `Liquid`.

**Comment by PaulNewton** [comment]
> @gretchen-willenberg As long as you're comfortable with opening the door to snippets from...`other sources` 

Point on, sorry was already putting in way too dense context on this dynamo of a feature so I glossed over some stuff in the [nit](https://github.com/Shopify/dawn/issues/299#issuecomment-892232117) 😆.

So the thinking is, as long as `advanced customizations` is in the mix the implication is clear to **informed** merchants that by using this they are leaving the sphere of the `basic customizations` design support policy. 
While I'd love to see the encouragement of possibilities , that the ambiguous "`other sources`" gives to any downstream end user,  it does come with a type of support pressure that no matter how far downstream the theme gets shopify will probably get a consistent burden of no-op support tickets stemming from not just `other sources` but it acting as a force multiplier against `advanced customizations` requests that get rejected by policy.

So the internal decision to leave or omit `other sources` could boil down to does shopify ~~believe~~ know that enough merchants using a liquid-section who read the words `advanced customizations` will fully understand what they are doing to the theme is **not** supported and they are on their own path and reliant on whatever 'other sources' means to them.

Or until usage data comes in or a/b testing is done `other sources` is too heady , _too broad_,  so just put the thing on ice 😁.

_A gauche oldschool solution is the placeholder content just has the url to the design support policy docs.. a scope creep solution is any "advanced" features section comes with an optin requirement checkbox acknowledging the risk to enable the content._

**Review by sofiamatulis — APPROVED** [review]
🚢

**Comment by ludoboludo** [comment]
We can maybe revisit if we see that it's generating too many support tickets. Or get feedback from the theme support team about it.

**Review by gretchen-willenberg — COMMENTED** [review]
I would reassign my review to Nick. He signed off on the previous version of the support copy.

**Review by sofiamatulis — APPROVED** [review]

**Pull request merged**
