### PR TITLE
Correcting all the shopify theme check errors

### LINKED ISSUE #2944: Theme Check passes in CI but not locally with `shopify theme check`
## Describe the current behavior
It appears, [as of this commit](https://github.com/Shopify/dawn/commit/7d02769927d723f74166885690d9d0ee53266401), that the Theme Check is passing on CI. However, when running `shopify theme check` locally on a fresh repo cloned from the same commit, `shopify theme check` reports `291 files inspected, 29 offenses detected, 20 offenses auto-correctable`

## Describe the expected behavior
If the Theme Check passes in CI, it should also pass locally given that the repos are exactly at the same point in time.

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 11.0.0, from commit https://github.com/Shopify/dawn/commit/7d02769927d723f74166885690d9d0ee53266401
- Chrome Version 114.0.5735.198
- macOS Version 12.5.1

## Possible solution
I'm unsure of how to fix this.

## Additional context/screenshots
Screen Shot 2023-08-05 at 6 05 13 PM

### PR DESCRIPTION
**Pull request by abhishekjani08**
### PR Summary: 
The shopify dawn theme consisted of many errors and warning of Json schema not proper, Loading lazy for one image and using Liquid tags wherever needed.
I have correct all the errors in this PR.
All the 29 offenses are corrected perfectly.

### Why are these changes introduced?

Fixes #2944 

### What approach did you take?

- **Fixed JSON Schema Issues:** Describe how you addressed JSON schema errors in the Dawn theme. Include any specific changes made to resolve these issues.

- **Lazy Loading Image:** Explain the implementation of lazy loading for the image. Provide details on the changes made to incorporate the `loading="lazy"` attribute.

- **Liquid Tags Usage:** Discuss where and how you incorporated Liquid tags where needed. Provide examples or specific instances where Liquid tags were added or modified.

### Visual impact on existing themes
No visual impact, everything remains the same.
It just emphasises the code and the code usuabilty for all the users as now there are no more warnings left.

## Before:
Previously there were these many errors:

And the errors were:

## After:
image

### Checklist
- [x] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [ ] Requested review from UX (Only for changes that are affecting the experience or perceivable visual details)
- [x] Created a ticket for the [help.shopify.com](https://help.shopify.com) documentation team about updates to theme settings. (Internal-only task)
- [x] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [x] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [x] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [x] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [x] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

### CODE REVIEW

**Comment by joshistoast** [comment]
I'd suggest also modifying `.prettierrc.json` to also prevent vscode from automatically un-fixing these on save

**Comment by joshistoast** [comment]
`.vscode/settings.json`
```json
{
  "editor.formatOnSave": false,
  "[javascript]": {
    "editor.formatOnSave": true
  },
  "[css]": {
    "editor.formatOnSave": true
  },
  "[liquid]": {
    "editor.formatOnSave": false
  }
}
```
Perhaps we should change liquid formatting on save to `false` since prettier by nature always formats liquid against what Shopify's theme check recommends.

**Comment by abhishekjani08** [comment]
yess you are correct @joshistoast 
Thus, shopify theme check would also work perfectly and will give us no errors!

**Comment by KaichenWang** [comment]
@abhishekjani08 Thank you for making these changes! I've created a new [PR](https://github.com/Shopify/dawn/pull/3283) which addresses these and a few addtional theme check offences. I've added you as a collaborator in that PR.

**Pull request closed without merging**
