### PR TITLE
Added custom liquid block to product page

### LINKED ISSUE #42: Product Page: Custom Liquid Block
This ticket proposes the addition of a custom liquid block to :

- [ ] 1. the main section of the product page. 
- [ ] 2. featured product section 

**What this solves**
Similarly to the Custom Liquid Section, this can let merchants (and theme specialists) make slightly more advanced theme customizations without going off the upgrade path.

-----

From @andrewetchen 

> Add a Custom Liquid page block to [main-product.liquid](https://github.com/Shopify/dawn/blob/main/sections/main-product.liquid)
> 
> <details>
>   <summary>Custom Liquid - Page Block </summary>
> 
> image
> 
> </details>
> 
> - Add the following: I added it before `{%- when 'description' -%}`
> 
> ```liquid
> {%- when 'liquid' -%}
>   {{ block.settings.custom_liquid }}
> ```
> 
> - Add the following schema block setting:
> 
> ```json
> {
>   "type":"liquid",
>   "name":"Custom Liquid",
>   "settings": [
>     {
>       "type": "liquid",
>       "id": "custom_liquid",
>       "label": "Custom Liquid"
>     }
>   ]
> },
> ```

### PR DESCRIPTION
**Pull request by tyleralsbury**
**Why are these changes introduced?**

Fixes #42 

**What approach did you take?**

Pretty straight-forward. I just added a block with a Liquid setting with no limit to how many can be added to the main product section.  I decided against wrapping it in any sort of container, to give the merchant full control over how they want it to output.  If they want it to be block, they can wrap the Liquid in a `<div>` themselves, for example.

**Demo links**

- [Store](https://os2-demo.myshopify.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=120917491734)
- [Editor](https://os2-demo.myshopify.com/admin/themes/120917491734/editor)

**Checklist**
- [x] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [x] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [x] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [x] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [x] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

### CODE REVIEW

**Review by sofiamatulis — DISMISSED** [review]
Nice 👍 Code looks good and works well. I see the original issue asks for it on featured product as well - should we create a separate issue?

**Comment by tyleralsbury** [comment]
> featured product as well - should we create a separate issue?

I've added it to the issue for Featured Product so I don't forget it on there.

**Review by KaichenWang — DISMISSED** [review]
Looks good, would just need to add `label` key to the locale json

**Review by LucasLacerdaUX — DISMISSED** [review]

**Comment by LucasLacerdaUX** [comment]
> I've added it to the issue for Featured Product so I don't forget it on there.

Just as a side note: I've already added this same block to the #261 PR, following Kai's suggestion above.

**Comment by tyleralsbury** [comment]
Fixed them, thanks @KaichenWang

**Review by LucasLacerdaUX — APPROVED** [review]

**Pull request merged**
