### PR TITLE
Fix typo in image-banner

### PR DESCRIPTION
**Pull request by leesiongchan**

### CODE REVIEW

**Review by ludoboludo — APPROVED** [review]
Thanks for the fix and creating the PR @leesiongchan

**Review by KaichenWang — APPROVED** [review]

**Comment by ludoboludo** [comment]
Hey @leesiongchan, you can sign the CLA and then you should be able to merge the PR. Otherwise I can merge it myself in the morning on friday 👍

**Comment by leesiongchan** [comment]
I already signed it, not sure why it still showing x.

**Comment by ludoboludo** [comment]
Hey @leesiongchan, we have seen it happen when the username and email weren't setup locally. So you could try and run: 
```
git config --global user.name "githubHandle"
git config --global user.email "yourEmail"
```
In your terminal and we shall see if it fixes the issue if you ever open another PR 👍

**Pull request merged**
