### PR TITLE
[Card settings] Search results page 

### LINKED ISSUE #1821: [Card settings] Search results page - card settings per card type
- [x] The cards with "page" tag – will be tied to the blog card settings
cards with page tag

- [x] The cards with "blog" tag – will be tied to the blog card settings
cards with blog tag

- [x] The product "cards" - will be tied to the product card settings
product cards

- [x] Add sub-copy "Blog card styles also apply to page cards in search results. To change card styles, update your theme settings." under blog card section on search results settings.
search results settings

### PR DESCRIPTION
**Pull request by sofiamatulis**
**PR Summary:** 

- The cards with "page" tag – will be tied to the blog card settings
- The cards with "blog" tag – will be tied to the blog card settings (existing)
-  The product "cards" - will be tied to the product card settings (existing)
-  Add sub-copy under blog card section on search results page settings "Blog card styles also apply to page cards in search results. To change card styles, update your theme settings." 

updates to the blog card section

**Why are these changes introduced?**

Fixes #1821.

**What approach did you take?**
Added the article class to the page card.

**Testing steps/scenarios**
- [ ] Test all card settings in the search cards (page cards are the new ones)
- [ ] Check if subcopy is there

**Demo links**
_Please include a link to a demo store that includes preconfigured sections and settings to allow reviewers to easily test the features you are working on._

- [Editor](https://os2-demo.myshopify.com/admin/themes/128311722006/editor)

**Checklist**
- [ ] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [ ] Notified the [help.shopify.com](https://help.shopify.com) team about updates to theme settings (current contact: Kimli)
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

### CODE REVIEW

**Review by katycobb — COMMENTED** [review]
Help text shows up as expected 👍

**Review by duygukalaycioglu — APPROVED** [review]
Approving the setting logic per each card type, looking great! 🎉

**Comment by sofiamatulis** [comment]
> We have received a translation request but there is a question blocking translation work. Your help is needed.
> 
> ### Click the following links to answer the questions
> ⚠️ Replying directly to this comment in GitHub will not work! 🙅‍♀️
> 
> * [ ]  Hi team, can you please clarify what "styles" means in this context? Does it refer to the look of the card? Thanks in advance. [Answer here.](https://translation-platform.shopify.io/repos/Shopify/dawn/components/merchant/issues/948fb043c154)
>   https://github.com/Shopify/dawn/blob/0b3052e9f7e2e55ea26557fe2708e84f11eac5bc/locales/en.default.schema.json#L1895
> 
> #### Not your issue?
> Forward the issue to someone with more context; please don't leave this pending. 🙏
> 
> #### Questions?
> Hop in the [#help-i18n-and-translation](https://shopify.slack.com/messages/C7TJQLVC7) Slack channel.

@katycobb @duygukalaycioglu  Could one of you reply in the link above for translations? :)

**Comment by andrewetchen** [comment]
@duygukalaycioglu and @sofiamatulis 

Thanks for clearing that up, @duygukalaycioglu my apologies ❤️

I was checked out on Sofia's `search-cards` branch (which is on version: `6.0.0`) and I ran `shopify theme serve` and didn't see it was on version `6.0.0`.

This was what I was seeing on Sofia's `search-cards` branch:  https://github.com/Shopify/dawn/blob/459c774a22d9ad865dbeeed9c2a83d71af0f0cb3/locales/en.default.schema.json#L104

False alarm / a good sanity check on my part and I'm glad it was changed to **Position on cards**. Admittedly, it's very difficult to keep track of all the changes or at least being aware of them.

**Pull request merged**
