### PR TITLE
Blog zoom in duration

### LINKED ISSUE #421: Inconsistent "Zoom In" Animation on Blog Post hover
The zoom in animation upon hover of a blog post is too speedy. 

Let us make sure it uses the same subtle speed than what it used on Collage and Collection Cards. 

[Recording](https://screenshot.click/21-13-h1dh1-wtfaq.mp4)

### PR DESCRIPTION
**Pull request by ludoboludo**
**Why are these changes introduced?**

Fixes #421 

**What approach did you take?**

Change the variable it's using for the animation. Exactly what's mentioned in the issue, to change the duration from `200ms` to `500ms`. 

**Other considerations**

**Demo links**

- [Store](https://os2-demo.myshopify.com/?preview_theme_id=126324539414)

**Checklist**
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

**To test** 
Go into the footer menu and click on `News` then hover over the blog images.

### CODE REVIEW

**Comment by ludoboludo** [comment]
Good point. I think because the image/cards are smaller then the duration is a bit faster 🤔

**Comment by Oliviammarcello** [comment]
> Probably a question for @Oliviammarcello, but should this change apply to [article cards in search results](https://screenshot.click/02-56-sz1hk-c8toy.png) as well? Seems like a similar enough use case. I noticed that's also currently using 200ms. Otherwise lgtm.

Good point, I think ludo is right. It should match the speed that the other search cards have, like the products cards.

**Comment by Oliviammarcello** [comment]
Other than updating the speed for the blog card on the search page it LGTM 👍

**Review by Oliviammarcello — APPROVED** [review]

**Review by sofiamatulis — APPROVED** [review]
Nice 👌

**Pull request merged**
