### PR TITLE
Banner/Email banner follow ups

### PR DESCRIPTION
**Pull request by sofiamatulis**
**Why are these changes introduced?**

- Reorder classes for banner content so the alignment works: https://github.com/Shopify/dawn/pull/900#discussion_r764109263
- Remove outline offset since it's already assigned https://github.com/Shopify/dawn/pull/900#discussion_r764219747
- Remove `text_style` uppercase from banner email since the block is an `rte` https://github.com/Shopify/dawn/pull/900#discussion_r764124705

**Checklist**
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

### CODE REVIEW

**Comment by katycobb** [comment]
@sofiamatulis not totally sure if this is the correct issue, please let me know if not! For image banner, we'd like to add help text under the `Desktop content position` field to explain how this behaves on mobile: `Position is automatically optimized for mobile`.

Let me know if you need more info. cc @wiktoriaswiecicka

**Comment by sofiamatulis** [comment]
> @sofiamatulis not totally sure if this is the correct issue, please let me know if not! For image banner, we'd like to add help text under the `Desktop content position` field to explain how this behaves on mobile: `Position is automatically optimized for mobile`.
> 
> Let me know if you need more info. cc @wiktoriaswiecicka

@katycobb Since this will require new translations I will add this to this existing issue and we will create a follow up PR to include it https://github.com/Shopify/dawn/issues/959 :)

**Review by martinamarien — APPROVED** [review]
Looks good to me. Thanks Sofia.

**Review by tyleralsbury — APPROVED** [review]
🚢

**Pull request merged**
