### PR TITLE
cart add line_item.properties ajax json support

### PR DESCRIPTION
**Pull request by michaelhaessig**
**Why are these changes introduced?**
Hi Team, 

the current implementation of the productForm.onSubmitHandler does not correctly submit custom line item properties to the Ajax cart api. 

the function serializeForm in global.js returns the following JS object:  ( 2 custom properties defined in the form )

````
{
  "quantity": "1",
  "form_type": "product",
  "utf8": "✓",
  "id": "40307349094593",
  "properties[name]": "michael",
  "properties[upload]": "https://upload.dev.cloudlift.app/s/dev/cloudlift-dev-store2/SVutmqCkG2.png",
  "sections": [
    "cart-notification-product",
    "cart-notification-button",
    "cart-icon-bubble"
  ],
  "sections_url": "/products/upload-lift"
}
````

This object is sent via "fetch" with the content-type "application/json".   The Shopify ajax api will not detect the line item properties in this format.  

The docs state that the properties have to nested in the "properties" field: https://shopify.dev/api/ajax/reference/cart#add-line-item-properties

Lots of apps are using custom line item properties in the product form, the current implementation breaks all of them. 

**What approach did you take?**

This pull request extends the serializeForm function to auto nest the line item properties which results in the following JS object: 

````
{
  "quantity": "1",
  "form_type": "product",
  "utf8": "✓",
  "id": "40307349094593",
  "properties": {
    "name": "michael",
    "upload": "https://upload.dev.cloudlift.app/s/dev/cloudlift-dev-store2/3LuvMdXGbS.png"
  },
  "sections": [
    "cart-notification-product",
    "cart-notification-button",
    "cart-icon-bubble"
  ],
  "sections_url": "/products/upload-lift"
}
````

**Checklist**
- [X] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [X] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [X] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [X] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [X] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

### CODE REVIEW

**Review by swduerre — APPROVED** [review]
Checked changes with an file upload app which stoped working due to missing handling of line items properties.

Works again. All Good 👍

**Comment by tyleralsbury** [comment]
cc @tauthomas01 and @LucasLacerdaUX since they have the context from #509

**Comment by tauthomas01** [comment]
Hi @michaelhaessig ,

We merged https://github.com/Shopify/dawn/pull/509 last week so I was wondering if you had a chance to test and see if it looks good?

**Comment by michaelhaessig** [comment]
@tauthomas01  i can confirm that the other PR solved the issue.  I will close this pull request.

**Comment by M00NSH0T** [comment]
I'm not sure which issue this is more relevant to, but I'm having a pretty serious issue with line item properties on Dawn still. Everything works fine if I click 'add to cart' first and then checkout, but if I instead click 'buy now' none of the line item properties make it into the final order (as verified through the order's webhook json message that I send to pub/sub). 

I brought this up in #509 as well, but I'm not sure if maybe this might be the more relevant spot?

**Pull request closed without merging**
