### PR TITLE
Refactor + Optimize svg files

### PR DESCRIPTION
**Pull request by tyleralsbury**
Made files smaller. 🔻 

Now combined with Phase 2 - refactored the SVGs and rendering to have the parent context handle the width and height.

### CODE REVIEW

**Review by melissaperreault — COMMENTED** [review]
**Country/Region selector**
A few things are happening with this component, let me try to summarize!
- [x] Position of the label is too far from the down-caret if you compare with production
- [ ] As you search a query, the input shrinks in width as you type. In production it has a fixed width
- [x] The checkmark of the selected option is [not vertically centered align with its label](https://screenshot.click/21-19-bcl0z-az8h3.png)


https://github.com/user-attachments/assets/293bad64-6515-455c-a24c-c7739873d488



**Search loading spinner**
- [x] It lost thickness in the way ([Video reference](https://screenshot.click/21-19-j6wfv-pl9ex.mp4))

**Comment by tyleralsbury** [comment]
> As you search a query, the input shrinks in width as you type. In production it has a fixed width

It doesn't seem to be a fixed width in production.  It doesn't collapse down as small as here, but it does shrink as the text gets smaller.  I'll set a min-width.

**Comment by melissaperreault** [comment]
**Inventory status block**
- [ ] Some odd alignment over there ([Visual reference](https://screenshot.click/21-27-24aut-koic4.png))

**Comment by melissaperreault** [comment]
**Mobile drawer menu**
- [ ] Login icon so smolll 

| Expected | Current |
|--------|--------|
|  |  |

**Comment by tyleralsbury** [comment]
Merging this to the Phase 1 PR.  We've gotten the value we could out of the phase approach.

**Review by m74278803-cmyk — COMMENTED** [review]
#3869 assets/component-slideshow.css

**Pull request merged**
