### PR TITLE
Improved country selectors

### PR DESCRIPTION
**Pull request by hamideha**
# Original PR with reviews and discussion https://github.com/Shopify/dawn/pull/3135
### PR Summary: 

**Designer responsible:** @designrichly 
**Developer responsible:** @hamideha 

Improves the country selectors in Dawn.

1. Adds basic search functionality
2. Shows store's popular countries at the top of the list. This uses `popular?` on the Country object in liquid which is true for at most 4 countries on a shop.
3. Improves mobile responsiveness of country selector. On mobile instead of having a dropdown, the selector is essentially a modal dialog.
4. Some UI improvements
   - Move the country to show up before the currency
   - Use a checkmark instead of underline to indicate that a country is selected

### Why are these changes introduced?

As part of the mission of increasing cross-border conversion, we decided to improve the first piece of the online store that a cross-border buyer interacts with.

User-testing was done with a prototype of the new selectors and they outperformed the current selectors. The users used the popular countries, they often searched for countries, and they commented on how the current selectors are less user-friendly than the prototype. 

### What approach did you take?

The code that was added, for the most part, follows patterns already established in Dawn. Nothing unique or out of the ordinary. Possibly the only thing that is different is the search functionality (it's more of a filter than search); it uses a very naive and basic filtering approach with string matching (`.includes(string)`) 

The no-js approach to country selectors is exactly the same as it is today; using a browser-native select element.

### Decision log

Some UX decisions that were made:
| # | Decision | Alternatives | Rationale | Downsides |
|---|---|---|---|---|
| 1 | By default we only popular countries if there are more than 9 total countries and if there is more than 1 popular country |  | If there are less than 9 countries, the popular country would appear very close to its identical copy in the regular list |   |
| 2 | We only show the search box if there are more than 9 countries |  | The list would be short enough that users don't have to search |   |

### Visual impact on existing themes
1. New search box in the country selector
2. New mobile design
3. Small UI nits

### Testing steps/scenarios
Just play around with the country selector and the search functionality. There are 3 places that the country selector could show up: the header, the footer, and the announcement bar (only on desktop).

### Demo links
Store without popular countries:
- [Store](https://hamidehs-store.myshopify.com/)
- [Editor](https://admin.shopify.com/store/hamidehs-store/themes/162597994518?key=snippets%2Fcountry-localization.liquid)

Store with popular countries (Note that the popular countries are hardcoded):
- [Store](https://mylittleearthling.myshopify.com/)
- [Editor](https://potteryplants.myshopify.com/admin/themes/137609019605?key=snippets%2Fcountry-localization.liquid)

All 1st party themes:
[Sense](https://hamidehs-store.myshopify.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=162694168598)
[Crave](https://hamidehs-store.myshopify.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=162694201366)
[Craft](https://hamidehs-store.myshopify.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=162694266902)
[Studio](https://hamidehs-store.myshopify.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=162694299670)
[Taste](https://hamidehs-store.myshopify.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=162694332438)
[Colorblock](https://hamidehs-store.myshopify.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=162694365206)
[Ride](https://hamidehs-store.myshopify.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=162694397974)
[Refresh](https://hamidehs-store.myshopify.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=162694430742)
[Origin](https://hamidehs-store.myshopify.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=162694463510)
[Publisher](https://hamidehs-store.myshopify.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=162694496278)
[Spotlight](https://hamidehs-store.myshopify.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=162694529046)

### Checklist
- [x] Requested review from UX (Only for changes that are affecting the experience or perceivable visual details)
- [x] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [x] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [x] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [x] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [x] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

### CODE REVIEW

**Review by slucaskim — APPROVED** [review]

**Comment by tyleralsbury** [comment]
@eugenekasimov can you take a look at this?  It looks like you had been heavily involved in the previous review.

**Review by eugenekasimov — APPROVED** [review]
Everything works as expected 👍

The only thing I wish I could test is the case when the list of available countries is less than nine and we don't render the search bar but unfortunately I didn't figure out how to change `available countries size` to something less than nine.

**Review by designrichly — APPROVED** [review]
Using the tick to indicate current country means that aligning the countries in the list and the search is not consistently possible. It also means that padding on the right side on desktop is large to keep the currencies and the country list equally padded. I think these are the best solutions in the circumstances without reverting to the underline approach for the selected country.

**Comment by melissaperreault** [comment]
👋 Hi team! Have we consider putting the focus on the search input when interacting with the component? Like we do with search? Having to click/tab in the search field after clicking/tabing the selector feels like an extra step we could avoid. What do you think? 

([Video reference](https://screenshot.click/09-37-3wuul-gya51.mp4))

**Pull request merged**
