### PR TITLE
Add total_duties to customer account order page

### PR DESCRIPTION
**Pull request by minh-tran-shopify**
**Why are these changes introduced?**
- Duties is a new feature for merchants selling internationally. We expose the amount of duties on an order view through the total_duties attribute. This PR updates the Dawn theme to display the duties total on the customer account order page.

**What approach did you take?**
- Since `total_duties` [is an attribute on order object](https://shopify.dev/api/liquid/objects/order#order-total_duties), I used this attribute to display the total duties. In cases where duties are not applicable (merchants do not collect duties, or the order is domestic), the duties line is not rendered.

<details>
<summary>Here's an example of duties being rendered</summary>
Screen Shot 2022-02-16 at 3 56 26 PM
</details>

**Testing steps/scenarios**
Enable the duties and taxes incoterm feature. Set up shipping to an international country. In taxes and duties setting page, collect duties in that international country. Sign up / Log into an account. Checkout.
- [x] An international order in a country that the store has enabled duties for, and the order total is above a country's de minimis (e.g: > $800 for orders in the US) -> Duties should show up
- [x] An international order in a country that the store has enabled duties for, but the order total is below a country's de minimis (e.g: < $800 for orders in the US) -> Duties should show up but the value is $0
- [x] A domestic order -> Duties should _not_ show up as it is not applicable

**Demo links**
_Please include a link to a demo store that includes preconfigured sections and settings to allow reviewers to easily test the features you are working on._

- [Store](https://minhtranteststore.myshopify.com/)
    - Please sign up for an account _or_ log into this customer account:
        - testing123@shopify.com
        - 123456 
- [Editor](https://minhtranteststore.myshopify.com/admin/themes/126482841656?key=templates/customers/order.liquid&line=252)

**Checklist**
- [x] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [x] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [x] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [x] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

### CODE REVIEW

**Review by KaichenWang — APPROVED** [review]
Looks good. Just awaiting translations

**Review by martinamarien — APPROVED** [review]
Looks good. Thanks Minh.
I'll approve again once all translations come back.

**Review by melissaperreault — APPROVED** [review]
Looks good! 
Unrelated,  At checkout, I was wondering why we see `Taxes` prior to `Duties`, it was interesting to witness.  ([Video reference](https://screenshot.click/22-02-srd8i-m8snd.mp4))

**Review by martinamarien — CHANGES_REQUESTED** [review]
Hey Minh, looks like a bunch of files were modified by an app on your store and sent back as commits on your branch. Would you mind reverting those two commits from your shop? Once that's done, I'll re-approve. Thanks!

**Comment by minh-tran-shopify** [comment]
> Hey Minh, looks like a bunch of files were modified by an app on your store and sent back as commits on your branch. Would you mind reverting those two commits from your shop? Once that's done, I'll re-approve. Thanks!

@martinamarien Hey Martina, thanks for letting me know. I have removed the 2 commits from the branch

**Review by melissaperreault — APPROVED** [review]
🎉

**Pull request merged**
