### PR TITLE
Quick Add: Fix button overflow on mobile carousel 

### LINKED ISSUE #1566: [QUICK ADD] Button overflow on mobile carousel product cards
**Describe the current behavior**
The quick add button is overflowing outside the product card on mobile carousels. It makes the grid-gap disappear visually for the buyer (see screenshots). Found this bug in the Featured collection section on the Cart template.

**Describe the expected behavior**
The button should not overflow outside of the product card to maintain the grid-gap if any.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 4.0.0
- Chrome Version 100.0.4896.60 (Official Build) (x86_64)
- macOS Version 12.3

**Possible solution**
Tricky since ideally, the button should maintain its appearance without a text break. Perhaps making the button's padding or the overall size smaller on mobile?

**Additional context/screenshots**
Screen Shot 2022-03-31 at 10 53 09 AM
Screen Shot 2022-03-31 at 10 51 26 AM

### PR DESCRIPTION
**Pull request by LucasLacerdaUX**
**Why are these changes introduced?**
Fix button overflow on mobile product cards.

Fixes #1566.

**What approach did you take?**
Added `box-sizing: border-box`.

**Testing steps/scenarios**
- [ ] Add a `Featured Collection` section to the page:
  - [ ] Enable quick add button
  - [ ] Enable swipe on mobile
  - [ ] Set `Number of columns on mobile` to `2 columns`
- [ ] Test on mobile viewport

**Before & After**
image image

**Demo links**
- [Store](https://os2-demo.myshopify.com/?preview_theme_id=127787532310)
- [Editor](https://os2-demo.myshopify.com/admin/themes/127787532310/editor)

### CODE REVIEW

**Review by andrewetchen — APPROVED** [review]
Thanks for fixing this, Lucas. [Looks good to me](https://user-images.githubusercontent.com/28404165/161142567-d5af4a9b-1c28-4e9e-a85e-41212a6c7110.png)

- [x] Add a `Featured Collection` section to the page:
  - [x] Enable quick add button
  - [x] Enable swipe on mobile
  - [x] Set `Number of columns on mobile` to `2 columns`
- [x] Test on mobile viewport

**Review by melissaperreault — COMMENTED** [review]
Thank you Lucas! 🎉 

**Questions/observations**
- [ ] When words are long, the button [would still overlap the next column](https://screenshot.click/22-03-5u4m6-1h3vb.png)
- [ ] If one of the 2 buttons label in [other languages are longer](https://screenshot.click/22-03-hxzo6-vqmcn.png), can we enlarge vertically all of them? It could help enclose the grid  structure we are offering with the bottom alignment. In my example, I made "Choose options" longer to stress test this example.


**Out of scope for this PR**
Mostly consider a _not cute_ find, will open an issue just to document
- Noticed the focus is [overlapping text above](https://screenshot.click/22-03-49olr-ls03y.png) on the product title
- The focus around the [View full details](https://screenshot.click/22-03-g1jmi-x80xy.png) link is large

**Comment by andrewetchen** [comment]
> > If one of the 2 buttons label in [other languages are longer](https://screenshot.click/22-03-hxzo6-vqmcn.png), can we enlarge vertically all of them? It could help enclose the grid structure we are offering with the bottom alignment. In my example, I made "Choose options" longer to stress test this example.
> 
> I'm not sure if that is possible. or at least, I don't know of any way to do it with the current HTML markup we have. If other devs have any idea, please let me know.

Let me know if this should be in a separate issue.

Adding to the point above, I think this button can also benefit from a `1rem` top and bottom padding in addition to the `1rem` left and right padding. From `padding: 0 1rem;` to `padding; 1rem;` essentially.

Also, certain translations can be quite long and are good examples where that additional top and bottom padding could be useful:

**Choose options**

- `hu`: _Válassz a lehetőségek közül_
- `vi`: _Chọn các tùy chọn_

**Add to cart**

- `nl`: _Aan winkelwagen toevoegen_
- `de`: _In den Warenkorb legen_
- `bg-BG`: _Добавяне към количката_
- `th`: _เพิ่มลงในตะกร้าสินค้า_

### Screenshots

<details>
  <summary>Current padding</summary>

  image

</details>

<details>
  <summary>1rem top and button padding</summary>

  image

</details>

<details>
  <summary>0.5rem top and button padding</summary>

  image

</details>

**Comment by bredowmax** [comment]
> > > If one of the 2 buttons label in [other languages are longer](https://screenshot.click/22-03-hxzo6-vqmcn.png), can we enlarge vertically all of them? It could help enclose the grid structure we are offering with the bottom alignment. In my example, I made "Choose options" longer to stress test this example.
> > 
> > 
> > I'm not sure if that is possible. or at least, I don't know of any way to do it with the current HTML markup we have. If other devs have any idea, please let me know.
> 
> Let me know if this should be in a separate issue.
> 
> Adding to the point above, I think this button can also benefit from a `1rem` top and bottom padding in addition to the `1rem` left and right padding. From `padding: 0 1rem;` to `padding; 1rem;` essentially.
> 
> Also, certain translations can be quite long and are good examples where that additional top and bottom padding could be useful:
> 
> **Choose options**
> 
> * `hu`: _Válassz a lehetőségek közül_
> * `vi`: _Chọn các tùy chọn_
> 
> **Add to cart**
> 
> * `nl`: _Aan winkelwagen toevoegen_
> * `de`: _In den Warenkorb legen_
> * `bg-BG`: _Добавяне към количката_
> * `th`: _เพิ่มลงในตะกร้าสินค้า_
> 
> ### Screenshots
> Current padding
> 1rem top and bottom padding
> 0.5rem top and bottom padding

As a German, I’d never use “in den Warenkorb legen” simply because it’s far too long. I’d rather go for “Hinzufügen”, which is German for “add”. Like jn this example:

Example:
A784F289-5600-46A0-9331-776EFBBA2F4A

**Comment by melissaperreault** [comment]
Great context @bredowmax, thanks! 
I believe Andrew was sharing examples to convey that we prefer not to assume all merchants will go with a specific language/word and help stress test that themes can scale in many directions depending on the language for instance. 

From a UX perspective we also cannot assume text will only live on 1 line based on the various settings combination that can impact the width of our components on smaller devices paired with all the languages that we can support.

**Review by melissaperreault — APPROVED** [review]
Thanks Lucas! Let's go forward here and move the other observations to different issues to align with product. 🙏 

Note on padding: I would be happy to go with a multiple of 4 if that makes sense to start systematizing spacing in general, in this case `0.8rem` for the top and bottom paddings.

**Pull request merged**
