### PR TITLE
Adjusted some footer alignment aspects

### PR DESCRIPTION
**Pull request by tyleralsbury**
**Why are these changes introduced?**

Fixes some footer alignment and spacing issues that came up during today's UX review.

**What approach did you take?**

Just some margin tweaks.

**Other considerations**

**Testing steps/scenarios**

* Test the footer with the newsletter
* Test the footer with the localization selector.  It was misaligned with the stuff in the footer's top container before.

**Demo links**
_Please include a link to a demo store that includes preconfigured sections and settings to allow reviewers to easily test the features you are working on._

- [Store](https://os2-demo.myshopify.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=127578767382)
- [Editor](https://os2-demo.myshopify.com/admin/themes/127578767382/editor)

**Checklist**
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

### CODE REVIEW

**Review by melissaperreault — APPROVED** [review]
Thanks Tyler! Works well!

Thanks for pushing the newsletter a little further too!

**Comment by tyleralsbury** [comment]
> @tyleralsbury @melissaperreault I just noticed this is happening on the localization selector and created an issue: #1343
> 
> I see that this is related to it, so maybe we can tackle it in this PR? If not a follow up 👍 Thought i'd bring it up before we merge

This is out of scope for what I wanted to achieve here, which was just a small alignment tweak + vertical rhythm adjustment.

**Comment by tyleralsbury** [comment]
@sofiamatulis would you mind reviewing this when you've got the chance?

**Review by ludoboludo — APPROVED** [review]
🚀

**Pull request merged**
