### PR TITLE
Fix missing internationalization on account page on order url

### PR DESCRIPTION
**Pull request by gregjotau**
https://github.com/Shopify/dawn/issues/739

### CODE REVIEW

**Comment by gregjotau** [comment]
@ludoboludo testet on fammestore.dk / famme.no, you can login with 

gregjotau@gmail.com
T8nrC4BQhBYgPy3

to test and see that it works.

**Comment by gregjotau** [comment]
To check the fix:

1. login to fammestore.dk
2. See that domain url is still fammestore.dk on order number link

This PR fixes this bug.

**Comment by gregjotau** [comment]
I have already signed the CLA so you have a bug here.

**Comment by ludoboludo** [comment]
Hey @gregjotau, since one of our team is looking at a fix for this issue, we won't be shipping this change you have in the PR. I will keep an eye on the issue they have created for it to see when a fix might ship for it 👍

**Comment by ludoboludo** [comment]
Thanks for bringing up this work around in the mean time 🥇

**Pull request closed without merging**
